sudo: false

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - pip install codecov
  - pip install clinner
  - ./make build

script:
  - ./make test --source

after_success:
  - codecov
