sudo: false
language: python
python:
- '3.6'
services:
- docker
env:
  global:
  - secure: SYMO0qbwWvK6V3FnjF8Fm3pg/WYEzDBqApNaW8I3k3PLnXshC+c1Ujnc5Hmy2VaysEmwy4Yea/XX9YN0LrvUHngSJ+EtDjSGiQKCuOpvwXL4DVE0kEBQcA2K5/88urtDrLEhlclMZzM6aYWBhGQ3rgtN1UNEd4SclCp/hPYJBrn9AJjuTYqjVXt4iwrlj68nI0ImT1+1+AqXxV7C6S6ewd1cJUlAPIzyDAMG47FYXk3NpyU+SycTveQYA8J5SsPquyjusmY6TIPP0Su6C6oPVkQC7OnNOCxxVYseu+cn/xO3gKCPyXjZsCi6WDTY1kEEHtFUEy6WkrggDFZg5fK9u5Wn7Ho/YLYLTkAL9E/yhaRfJnb/JIVwvKy+lj2RG+wyKOd4UMJANfIg2znQBEUFFOCkEqbXOCzALVN/RsfDj8w6aGI3E4LmKKaXpehfrGctkwEusxhk6HVd3KYFPT8jqXAwyY48GZbzkfHgkVY6kaYQVJp9zJ/Yw3eTpWASuzTHAQWF3+ZyKwYzH8sjrNmTw/L+ZHInOUAOARDAg+ThL+k1HytJ9sJYfJ7jU6WtiKGfBV3yhVD5bViM4U2urvkRjVglQSrz23Dg49h6Tc5K2R1EDxt6+ODUQ4nVI7pXJeZASV3Sl1nqns6ucctR3gptXdX1h72qZHaRgLJWfddrIpI=
  - secure: jQ1phRvivtBKM2k8oUL1ZbhwsQ/v/rnYh7Anml/bpRbpAFokFpg+kZqPfiCvvIzBDeEpTb9K/Z4+V8xGiE3UiB3xZvtsKVCe2XqkGeyMaUAga39E23bANpTX9hU2eBqCrKW/U5WpChAHb+Fng3YCe56EWIVLQ6KTb1cj2yhPhc6H1HXboyB1rgMe3dAA8da9tDpvyrYwrgAotBNRcjosI9XCtv3b1wcqtC9gm+b1/gdK1rbaC7z/zaMLmFHXfmqdF8gtjSJXuLxWR7qleq53YtKNrlpyr6pt5I8IyqgJm0AFulaGVkCQ7MqIIx2NlzodcfXomzcQNWpWPtYpm6RAUNr1rmCkzqwcbOAANz5sHItdOQ8dT7z3ecOvk4aT7jdGbHXIIAPgQ+9ae/WgZT0zFM8t0hJNeQw+Nj0w2sKcCFXsaHi6CMcQy1QV2Mkvoo+pq6mvAk1aXVLB5v/MgHpG7KZd+BJQCIJPlYauHmWqKUEsMbEvu1jj35c7mS/VlnixAvt0Q8AVtjOP4tt04wISUrwtWzPz6seAStNvW6XCibnjidJNvrYfebt6gPP6nBou4nbi5yEYeN8K3ByShMPb3Xd8I4sXeJuQ/7evH2owOg8bCre0OOFdgwhQrvnQbVu+x7C+rXHxYiunBu4iRZT+kAUmTu4wAo4M6gPSrmso6j8=
stages:
- test
- lint
- name: deploy
  if: branch = master
install:
- pip install -U clinner
jobs:
  include:
  - stage: lint
    before_script: "./make build"
    script: "./make lint"
  - stage: test
    before_install: pip install codecov
    before_script: "./make build"
    script:
    - "./make test"
    after_success: codecov -f .test_report/coverage.xml
  - stage: deploy
    before_script:
    - "./make build"
    - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
    script: "./make push"
notifications:
  slack:
    secure: F2BumJBNgTkxQR52FdIRXDS1ll3TFCxZT4po7SZ+rE6Tdg+RQqKxQJcUpZIipBpWBMqkabJD3+wAr2dsObaMtsmbzgOGYBznxGPW4ONnV9xMJecWWOO21U85vGSHsZ4HqakcWgX//giLvX7757slVMUvo+p/t7MqZmYjQNy4gjk9zOBTVN0YGV27BJyr2Me7yx54rd76pEdI3Lo5Rp6m2qcjS48dI3ZTngcLe4lCMkSuAH316STd26H5ELaT6brEL4qVMl56k4jeVZaiQdct/zgRagOArbsq8pzV4BBxXXxOZPCClzCtfTKJwfEhH1uW3WdAX7ahYN5EHh7llIg4muuOZ+bLU4jgMKcEGf4uRTVfok5R6hggetYc7lk+IM4ZR4v/5itZO7kTqodItdHqUmdJuxERLfD4x901UK/HlpQEbYB8J2zdier9ExTQBwqxos3Ag7dt6re9Ph8faYQNxoV2Zp2heT/WTPGLtMk3MNk38OkgWibP02StcIYP/hJVfat8tXRdqmIFzhP2pOvnF/T9CouVzWCm+I1CMQpLrVbq2nOKk8XtwDjJDxzPNK10kAq2X+TOyuE5YKl/PFneEIgI4DLU4XDF83GT6oeg2zNCq7oO7OM5XNvYgSQVo2nt9GZDa0UaF6D8lAyw2uDPDS3d8lxDCwBJOu16u6L9b/Y=
