#!/usr/bin/env python3.6
"""Run script.
"""
import argparse
import os
import sys
from typing import List

from clinner.command import Type as CommandType, command
from clinner.exceptions import ImproperlyConfigured
from clinner.run.main import Main as BaseMain

PYTHON = 'python3.6'
COVERAGE = 'coverage'
PROSPECTOR = 'prospector'
HEALTH_CHECK = 'health_check'
SCRAPY = 'scrapy'


@command(command_type=CommandType.SHELL)
def scrapy(*args, **kwargs) -> List[List[str]]:
    cmd = [SCRAPY]
    cmd += args
    return [cmd]


class Main(BaseMain):
    commands = (
        'clinner.run.commands.pytest.pytest',
        'clinner.run.commands.prospector.prospector',
        'scrapy',
    )

    def add_arguments(self, parser: argparse.ArgumentParser):
        parser.add_argument('--clinner-settings', default='goobox_nodes_scraper.plugin_settings.clinner:Development',
                            help='Clinner settings')
        parser.add_argument('--scrapy-settings', default='goobox_nodes_scraper.scrapy_settings.production',
                            help='Scrapy settings')

    def inject_app_settings(self):
        """
        Injecting own settings.
        """
        os.environ['SCRAPY_SETTINGS_MODULE'] = self.args.scrapy_settings
        os.environ['CLINNER_SETTINGS'] = self.args.clinner_settings


if __name__ == '__main__':
    main = Main()
    sys.exit(main.run())
