#!/usr/bin/env python3.6
"""Run script.
"""
import argparse
import os
import sys
from typing import List

from clinner.command import Type as CommandType
from clinner.command import command
from clinner.run.main import Main as BaseMain

SCRAPY = 'scrapy'


@command(command_type=CommandType.SHELL,
         parser_opts={'help': 'Scrapy commands'})
def scrapy(*args, **kwargs) -> List[List[str]]:
    cmd = [SCRAPY] + list(args)
    return [cmd]


class Main(BaseMain):
    commands = (
        'clinner.run.commands.black.black',
        'clinner.run.commands.flake8.flake8',
        'clinner.run.commands.isort.isort',
        'clinner.run.commands.pytest.pytest',
        'scrapy',
    )

    def add_arguments(self, parser: argparse.ArgumentParser):
        parser.add_argument('--clinner-settings', default='goobox_nodes_scraper.plugin_settings.clinner:Development',
                            help='Clinner settings')
        parser.add_argument('--scrapy-settings', default='goobox_nodes_scraper.scrapy_settings.development',
                            help='Scrapy settings')

    def inject_app_settings(self):
        """
        Injecting own settings.
        """
        os.environ['SCRAPY_SETTINGS_MODULE'] = self.args.scrapy_settings
        os.environ['CLINNER_SETTINGS'] = self.args.clinner_settings


if __name__ == '__main__':
    sys.exit(Main().run())
